version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
      - redis
      - meilisearch
  php:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    volumes:
      - .:/var/www/html:delegated
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    env_file:
      - ./.docker/mysql.env
  composer:
    build:
      context: .docker
      dockerfile: composer.dockerfile
    volumes:
      - .:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: .docker/php.dockerfile
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - .:/var/www/html
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "7700:7700"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
